baseURL = "https://test.canada.ca/gcds-protospace/"
title = "GCDS Protospace"
theme = "hugo-gcds"

# Language settings
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

# Disable taxonomy and term pages
disableKinds = ['taxonomy', 'term']

[languages]
  [languages.en]
    languageCode = "en-ca"
    languageName = "English"
    title = "GCDS Protospace"
    weight = 1
  [languages.fr]
    languageCode = "fr-ca"
    languageName = "Français"
    title = "Espace prototypage GCDS"
    weight = 2

[params]
  description = "An open-source prototyping space on GitHub will let us experiment with the GC Design System (GCDS) in a way that's fast, secure, and fully aligned with Government of Canada Digital Standards."